php7:
  build: .
  dockerfile: /etc/docker/dockerfile_php_7
  volumes:
    - ./sites:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - mysql


mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=magentoshop
  volumes: 
    - ./etc/mysql/db:/var/lib/mysql  
    - ./etc/mysql/init:/docker-entrypoint-initdb.d
